version: "3"
services:
  ros2_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID}
        USER_GID: ${GID}
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=42
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/home/rosdev/.Xauthority
      - ${HOME}/turtlebot3_ws:/workspace
      - /dev/dri:/dev/dri

